language: node_js

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

dist: trusty

sudo: required

before_script:
  - mysql -e 'create database costExplorerTest;'

node_js:
  - 10